services:
  futbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futbot
    env_file:
      - ./.env
    environment:
      FUTBOT_RUNTIME_DIR: /app/runtime
    volumes:
      - ./runtime:/app/runtime
    restart: unless-stopped
    init: true
